 mesh_files:
  gripper_connector:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/gripper_connector.dae
      material:
        name: "LightGrey"
        color: "0.69019607843137253944 0.69019607843137253944 0.69019607843137253944 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/gripper_connector.stl

  etiqueta:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/etiqueta.dae
      material:
        name: "Blue"
        color: "0.69019607843137253944 0.69019607843137253944 0.69019607843137253944 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/etiqueta.stl
    
  egh_80:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/egh_80.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/egh_80.stl
            
  almofada:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/almofada.dae
      material:
        name: "DarkGrey"
        color: "0.19607843137254901689 0.19607843137254901689 0.19607843137254901689 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/almofada.stl
    
  falangeta:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/falangeta.dae
      material:
        name: "Grey"
        color: "0.89803921568627453897 0.89803921568627453897 0.89803921568627453897 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/falangeta.stl
      
  falanginha:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/falanginha.dae
      material:
        name: "Grey"
        color: "0.89803921568627453897 0.89803921568627453897 0.89803921568627453897 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/falanginha.stl

  falange:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/falange.dae
      material:
        name: "Grey"
        color: "0.89803921568627453897 0.89803921568627453897 0.89803921568627453897 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/schunk/collision/falange.stl

  guia_dedo:
    visual:
      mesh:
        package: ur_description
        path: meshes/schunk/visual/guia_dedo.dae
      material:
        name: "Black"
        color: "0.2313725490196078538 0.2313725490196078538 0.2313725490196078538 1.0"
    collision:
      mesh:
      	package: ur_description
      	path: meshes/schunk/collision/guia_dedo.stl
        package: ur_description
        path: meshes/schunk/collision/guia_dedo.stl

