joint_limits:
#finger_right
  dedo_dir_joint:
    has_acceleration_limits: false
  	 has_effort_limits: true
  	 has_position_limits: true
  	 has_velocity_limits: true
  	 max_effort: 50.0
  	 min_effort: 25.0
  	 max_position: 0.040
  	 min_position: 0.0
  	 max_velocity: 0.04
    #finger_left
  dedo_esq_joint:
    has_acceleration_limits: false
  	 has_effort_limits: true
  	 has_position_limits: true
  	 has_velocity_limits: true
  	 max_effort: 50.0
  	 min_effort: 25.0
  	 max_position: 0.040
  	 min_position: 0.0
  	 max_velocity: 0.04
