egh80_joint_limits:
#
  dedo_dir_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceletation_limits: false
    max_acceleration: 0
  dedo_esq_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceletation_limits: false
    max_acceleration: 0
